version: "2"

services:
  redis:
      image: redis:latest
      container_name: redis
      restart: always
      networks:
        - fse_net
      ports:
        - 6379:6379
      volumes:
        - redis_data:/data
      healthcheck:
        test: [ "CMD", "redis-cli", "ping" ]
  task:
      image: task:latest
      container_name: task
      networks:
        - fse_net
      volumes:
        - task_data:/app
      healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:5001 || exit 1"]
      depends_on:
      - redis
      ports:
      - "5001:5001"

networks:
  fse_net:

volumes:
  redis_data:
  task_data: